export interface HabitTrack {
  id: string;
  name: string;
  fromLabel: string;
  toLabel: string;
  short: string;
  blurb: string;
  why: string;
  dailyMissions: string[];
  caution?: string;
}

export const habits: HabitTrack[] = [
  {
    id: "couch",
    name: "Couch to Course",
    fromLabel: "Sitting all day",
    toLabel: "Daily movement",
    short: "Stand up. Walk a little. Repeat.",
    blurb:
      "The couch isn’t the enemy. Never getting up is. This course turns sitting into short, doable movement.",
    why: "You don’t need a gym membership. You need a start line you can actually cross.",
    dailyMissions: [
      "Stand up and stretch for 60 seconds. That’s mile 1.",
      "Walk to the end of the block and back. Slow is fine.",
      "Do 10 sit-to-stands from a chair. Rest whenever you want.",
      "Take a 5-minute walk after one meal today.",
      "Park farther away, or get off one stop early.",
      "Walk for 15 minutes. Any pace. Mile 6 is in the books.",
      "Split two 10-minute walks across the day.",
      "20 easy bodyweight squats. Hold a counter if you need it.",
      "Walk during one phone call today.",
      "A 20-minute easy walk. You can talk the whole time.",
      "Take the stairs once instead of the elevator.",
      "10 push-ups — knees or toes, your call.",
      "25-minute walk. You’re at the half. Keep it easy.",
      "When you crave the couch, move for 3 minutes first.",
      "30 minutes of walking, or 3 × 10 minutes.",
      "Dance or shadowbox through one full song.",
      "Add about 2,000 steps vs. yesterday. Estimate is fine.",
      "40-minute walk, split however you like.",
      "3 rounds: 8 squats, 8 wall push-ups. Breathe.",
      "The wall: show up for 10 minutes even if you don’t feel like it.",
      "45-minute walk. Easy pace. You’re in the kick.",
      "Add 5 minutes to whatever you did yesterday.",
      "Invite someone to walk this mile with you.",
      "50 minutes of movement, broken up is allowed.",
      "Repeat your favorite mile so far. Make it yours.",
      "26 minutes of movement. Cross the finish line.",
    ],
  },
  {
    id: "late",
    name: "Lights Out",
    fromLabel: "Late nights",
    toLabel: "Real sleep",
    short: "Protect the night so the day can work.",
    blurb:
      "Bad sleep makes every other habit harder. This course is 26 nights of getting to bed a little more honestly.",
    why: "You can’t out-hustle a wrecked night. Sleep is the recovery mile.",
    dailyMissions: [
      "Set a bedtime alarm 15 minutes earlier than usual.",
      "Charge your phone outside the bedroom tonight.",
      "Dim one light in the last hour before bed.",
      "No caffeine after 2pm today. Switch to water or herbal tea.",
      "Write tomorrow’s one task on paper, then close the loop.",
      "Screens off 20 minutes before you intend to sleep.",
      "Same wake time tomorrow, even if last night was messy.",
      "A 5-minute stretch or shower as your wind-down cue.",
      "Skip one late-night snack that usually keeps you up.",
      "Bedroom cooler if you can. Darker if you can.",
      "No scrolling in bed. If you wake, look at a wall, not a feed.",
      "Lights out at your target time. Imperfect still counts.",
      "Halfway: protect an 8-hour sleep window, even if you don’t fill it.",
      "The wall: go to bed when you said you would, not when you’re ‘done’.",
      "No extra episode. Tomorrow’s mile needs tonight.",
      "10 slow breaths in bed before you reach for anything.",
      "Keep tonight’s bedtime within 30 minutes of last night.",
      "Skip alcohol tonight if it usually wrecks your sleep.",
      "Morning light within an hour of waking — window or walk.",
      "Even if you’re behind, still start wind-down on time.",
      "Full wind-down: dim, charge out, bed on time.",
      "Protect sleep like a workout. It is one.",
      "Tell someone your lights-out time so it’s real.",
      "Earliest realistic bedtime of the course. Be kind about it.",
      "Repeat the night that felt best. Don’t invent a new system.",
      "Lights out on time. You finished a 26-night marathon.",
    ],
  },
  {
    id: "junk",
    name: "Real Plate",
    fromLabel: "Junk on repeat",
    toLabel: "Food that fuels you",
    short: "Swap one meal. Not your whole identity.",
    blurb:
      "Drive-thru on autopilot isn’t a moral failure. This course replaces one default at a time.",
    why: "Fitness doesn’t have to be hard. Dinner doesn’t have to be a project.",
    dailyMissions: [
      "Drink a full glass of water before the first snack.",
      "Add one piece of fruit or a vegetable to any meal.",
      "Eat sitting down, not standing over the sink or steering wheel.",
      "Swap one soda or energy drink for water.",
      "Build one plate with protein + something from the ground.",
      "Prep one easy backup: eggs, yogurt, leftovers, a sandwich.",
      "Pause 5 minutes before a craving. Then decide on purpose.",
      "Eat slowly for one meal. Put the fork down between bites.",
      "Skip one extra sauce, candy, or late-night delivery.",
      "Cook or assemble one simple meal at home.",
      "Protein at breakfast if you usually skip it.",
      "Grocery or pantry pass: one real-food item you’d actually eat.",
      "Halfway: two meals today that didn’t come from a window.",
      "When stressed, eat a planned snack instead of a spiral.",
      "Vegetables at lunch. Frozen counts. Canned counts.",
      "No phone for one meal. Taste the food.",
      "Pack tomorrow’s lunch or breakfast before you sleep.",
      "Drink water with dinner instead of a second sweet drink.",
      "A ‘good enough’ meal: protein, carb, color. That’s the bar.",
      "The wall: don’t start a reset diet. Just eat the next decent meal.",
      "Repeat a meal that already worked this course.",
      "Share a real meal with someone, even if it’s simple.",
      "Shop or prep for the last miles so hunger doesn’t choose.",
      "Three decent meals. Not perfect. Present.",
      "Eat like someone who is finishing, not starting over.",
      "One celebration meal that still includes a vegetable. You did 26 days.",
    ],
  },
  {
    id: "smoke",
    name: "Clear Air",
    fromLabel: "Smoking / vaping",
    toLabel: "More unhooked hours",
    short: "Delay it. Replace it. Stack the hours.",
    blurb:
      "This is a habit course, not a clinic. Delay, replace, and collect hours you didn’t light up.",
    why: "You don’t have to quit the planet today. You have to win the next 10 minutes.",
    caution:
      "This is habit support, not medical treatment. If you’re dependent, talk with a clinician or a quit line. You don’t have to do the hardest mile alone.",
    dailyMissions: [
      "Delay the first one by 10 minutes. Set a timer.",
      "Change one cue: different door, different chair, different pocket.",
      "Replace one session with a 5-minute walk.",
      "Drink water or chew gum through one craving.",
      "Log every time today — no judgment, just a count.",
      "Make one slot smoke-free (first hour after waking, or after meals).",
      "Tell one person you’re running this course.",
      "When the urge hits, box-breathe 4-4-4-4 once before deciding.",
      "Leave the device/pack in another room for one evening block.",
      "One full craving survived without lighting up. Notice it.",
      "Swap an afternoon one for tea, a walk, or a call.",
      "Clean one smoke-associated spot so it cues you less.",
      "Halfway: a 3-hour window with none. Any 3 hours.",
      "The wall: urge surfing — wait 10 minutes, then re-choose.",
      "Keep hands busy for one high-risk hour (dishes, weights, doodling).",
      "No smoking inside a specific place you care about today.",
      "Go to bed without the last one if that’s usually automatic.",
      "Count hours unhooked today. That’s the scoreboard.",
      "Plan tomorrow’s high-risk times and put a replacement next to them.",
      "If you slip, restart the next hour. Marathons have water stations.",
      "Longest smoke-free stretch of the course so far. Protect it.",
      "Do a mile of movement when the urge is loudest.",
      "Ask for backup if evenings are the hard part.",
      "Practice your ‘not right now’ line out loud once.",
      "Stack a smoke-free morning and a smoke-free evening.",
      "Finish with the longest unhooked window you can honestly claim.",
    ],
  },
  {
    id: "drink",
    name: "Clear Morning",
    fromLabel: "Drinking on autopilot",
    toLabel: "Nights you remember",
    short: "One less pour. One clearer morning.",
    blurb:
      "If the pour is the habit, this course puts water, food, and a stopping point in front of it.",
    why: "You don’t have to become a different person. You have to change tonight’s default.",
    caution:
      "This is habit support, not alcohol treatment. If stopping feels unsafe or you get withdrawal symptoms, get medical help.",
    dailyMissions: [
      "First drink of the day is water. Then decide.",
      "Eat a real meal before any alcohol.",
      "Cap tonight at a number you write down before the first pour.",
      "Swap one alcoholic drink for a non-alcoholic one.",
      "No drinking to ‘start’ a task. Do 10 minutes of the task first.",
      "Alcohol-free until a set time (example: 7pm).",
      "Tell someone your cap for tonight.",
      "Skip the extra round you’d usually say yes to.",
      "Go home one drink earlier than last time.",
      "An alcohol-free evening. Tea, shower, early bed.",
      "Measure pours if you drink. No freehand ‘whatever’.",
      "Plan a morning you want: write it, then drink in a way that allows it.",
      "Halfway: two alcohol-free days this week, including today if needed.",
      "The wall: sit with the urge for 15 minutes with a substitute in hand.",
      "No drinking alone tonight.",
      "If you drink, stop 3 hours before bed.",
      "Replace the after-work pour with a walk around the block.",
      "Keep a glass of water next to every drink.",
      "Choose the smaller glass. Finish it slower.",
      "If you blow the cap, stop there. Don’t ‘might as well’ the night.",
      "Alcohol-free night. Protect tomorrow’s miles.",
      "Do something with your hands at the usual pour time.",
      "Invite a friend into a low/no-drink plan for one evening.",
      "Shop for drinks you’ll actually enjoy that aren’t alcohol.",
      "Repeat the night that gave you the clearest morning.",
      "Finish with a night that matches the person you’re becoming.",
    ],
  },
  {
    id: "scroll",
    name: "Off the Feed",
    fromLabel: "Endless scrolling",
    toLabel: "Hours you keep",
    short: "Put the phone down. Pick your life up.",
    blurb:
      "The feed isn’t rest. This course buys back minutes that used to disappear.",
    why: "You don’t need a digital detox monastery. You need a few protected miles.",
    dailyMissions: [
      "First 10 minutes awake: no feed. Water, light, or feet on the floor.",
      "Turn off one non-essential notification.",
      "Move social apps off the home screen.",
      "A 20-minute phone-free block. Timer on.",
      "Charge in another room after a set hour.",
      "Scroll only after you do today’s tiny healthy action.",
      "Gray-scale the phone for the evening, or enable downtime.",
      "Leave the phone in another room for one meal.",
      "Replace one scroll session with a 10-minute walk.",
      "Unfollow or mute 5 accounts that spike you.",
      "No phone in the bathroom today. Weird. Effective.",
      "One hour of deep anything: walk, cook, lift, talk, read.",
      "Halfway: a 3-hour stretch with the phone in a drawer.",
      "The wall: when bored, wait 5 minutes before opening an app.",
      "Delete one app you open on autopilot. You can reinstall later.",
      "Text a real person instead of browsing strangers.",
      "Screens off 30 minutes before bed.",
      "Weekend-style: a morning with no social apps.",
      "Track pickups roughly. Awareness is the first mile.",
      "If you binge, close it and do a 3-minute reset. Don’t spiral.",
      "Phone-free workout, walk, or stretch. Just you.",
      "Give someone else your ‘hold this for an hour’ challenge.",
      "A hobby mile: 20 minutes on something with your hands.",
      "Longest phone-free block of the course. Repeat it.",
      "Set the finish-line rule you’ll keep after day 26.",
      "Wake, move, and eat before any feed. You finished.",
    ],
  },
  {
    id: "skip",
    name: "Show Up",
    fromLabel: "Skipping workouts",
    toLabel: "A body that expects you",
    short: "Ten minutes counts. Zero is the only miss.",
    blurb:
      "You don’t need motivation. You need a date with movement that’s too small to skip.",
    why: "Fit User was built on this: challenges you can actually finish with other people.",
    dailyMissions: [
      "Put tomorrow’s movement on the calendar like an appointment.",
      "10 minutes. Walk, stretch, or a video. Done is done.",
      "Lay out shoes or clothes where you’ll trip over them.",
      "15 minutes of any movement you won’t dread.",
      "Do the first 2 minutes. You’re allowed to stop after. Most won’t.",
      "A short session before excuses get a vote (morning if you can).",
      "Invite a friend, or post that you’re going. Social lock.",
      "20 minutes. Music on. No program shopping.",
      "Repeat a session you already survived. Familiar is a feature.",
      "If you miss a slot, do a 5-minute makeup the same day.",
      "Add one extra set or 2 extra minutes. Tiny overload.",
      "A ‘minimum viable workout’: 10 squats, 10 push-ups, 1-minute walk.",
      "Halfway: show up even if it’s ugly. Ugly still counts.",
      "The wall: 10 minutes on the days you want to skip most.",
      "Follow one simple video or playlist. Don’t invent a new plan.",
      "Train, then write one sentence: what you did. Proof.",
      "Go easier, not zero. Recovery session still is a session.",
      "25–30 minutes. That’s a real mile.",
      "Strength or hills or stairs — pick one hard-ish thing.",
      "Missed yesterday? Today is a water station, not a DNF.",
      "Same time as your best session so far. Ritual beats mood.",
      "Bring someone with you, even virtually.",
      "Almost-race effort for 8–12 minutes, then easy.",
      "Full session you’d be proud to log. Keep it simple.",
      "Dress rehearsal: the exact routine you’ll keep after the finish.",
      "Show up for 26 minutes. Take the finish-line photo.",
    ],
  },
  {
    id: "sugar",
    name: "Steady Energy",
    fromLabel: "Sugar crashes",
    toLabel: "Even fuel",
    short: "Cut the spike. Keep the sweet life.",
    blurb:
      "You’re not quitting joy. You’re stopping the crash that makes the next bad decision easy.",
    why: "Steady energy is how people stay in a marathon past mile 14.",
    dailyMissions: [
      "Eat something with protein before the first sweet thing.",
      "Swap one soda, juice, or sweet coffee for unsweetened.",
      "Read one label. If sugar is in the first three ingredients, notice it.",
      "Fruit instead of candy for one craving.",
      "No sweets until after a real meal today.",
      "Water first when you want sugar. Then decide.",
      "Keep a decent snack where the candy usually wins.",
      "Dessert after dinner only — not all afternoon.",
      "Cook or order a meal that isn’t sweet-first.",
      "If you have sugar, sit down and enjoy it. Don’t hide it.",
      "Skip the second round of dessert or the extra pump of syrup.",
      "A full day with no liquid sugar. Food sugar is still allowed.",
      "Halfway: notice energy at 3pm. That’s your scoreboard.",
      "The wall: craving + walk. Then choose.",
      "Pair any sweet with protein or fat (nuts, yogurt, cheese).",
      "Don’t grocery-shop hungry. Eat first.",
      "Replace late-night sugar with tea or a shower.",
      "One planned treat. The rest of the day stays boring-good.",
      "If you binge, the next meal is normal. No punishment restriction.",
      "Sleep matters for cravings. Protect tonight’s bedtime a little.",
      "Repeat the day that felt the most even.",
      "Tell someone your ‘one treat’ rule for the kick.",
      "Prep a sweet-ish but real option for the weekend.",
      "Two meals with protein, color, and no liquid sugar.",
      "Keep the rule you’d actually live with in week 5.",
      "Finish: celebrate with food you respect — including a planned treat.",
    ],
  },
];

export function getHabit(id: string): HabitTrack | undefined {
  return habits.find((habit) => habit.id === id);
}
